%% System block diagram for QET resilient filtering (WSN)
% Generates a compact conceptual system diagram and saves it as EPS.

clear; close all; clc;

%% 0) Figure and axes
fig = figure('Color', 'w');
ax  = axes('Parent', fig, ...
           'Position', [0 0 1 1], ...
           'XLim', [0 9], ...    % 画布宽度 0~9
           'YLim', [0 5]);       % 稍微矮一点
axis(ax, 'off');
hold(ax, 'on');

xMax = 9;
yMax = 5;
nx = @(x) x / xMax;
ny = @(y) y / yMax;

boxLW       = 1.1;
fontSz      = 10.5;
fontSzSmall = 9.5;

arrowLW   = 1.0;
headLen   = 10;     % 箭头头部长度
headWidth = 8;      % 箭头头部宽度

%% 1) Dynamic process block (left, 较小)
procX = 0.6; procY = 2.0; procW = 1.6; procH = 1.3;
rectangle('Position', [procX procY procW procH], ...
          'Curvature', 0.12, ...
          'LineWidth', boxLW);

text(procX + procW/2, procY + procH*0.6, ...
    {'Dynamic process', '$x_k$'}, ...
    'Interpreter', 'latex', ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'middle', ...
    'FontSize', fontSz);

%% 2) Sensor node block (middle，略瘦)
sensX = 3.0; sensY = 1.6; sensW = 2.1; sensH = 2.3;
rectangle('Position', [sensX sensY sensW sensH], ...
          'Curvature', 0.10, ...
          'LineWidth', boxLW);

text(sensX + sensW/2, sensY + sensH*0.75, ...
    {'Sensor node $i$', ...
     'Innovation: $\epsilon_k^{i}$', ...
     'Event trigger: $\|\epsilon_k^{i}\|\ge\gamma_i$', ...
     'Quantizer: $\mathcal{Q}_{\Delta_i}(\cdot)$'}, ...
    'Interpreter', 'latex', ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'middle', ...
    'FontSize', fontSzSmall);

text(sensX + sensW/2, sensY - 0.35, ...
    '$i = 1,\dots,M$', ...
    'Interpreter', 'latex', ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'middle', ...
    'FontSize', fontSzSmall);

%% 3) Fusion center block (right，缩窄)
fusX = 6.0; fusY = 1.9; fusW = 1.8; fusH = 1.9;
rectangle('Position', [fusX fusY fusW fusH], ...
          'Curvature', 0.10, ...
          'LineWidth', boxLW);

text(fusX + fusW/2, fusY + fusH*0.6, ...
    {'Fusion center', ...
     'QET Kalman filter', ...
     '+ outlier rejection'}, ...
    'Interpreter', 'latex', ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'middle', ...
    'FontSize', fontSzSmall);

%% 4) Arrows and labels（加粗箭头头部）

% 4.1 Process -> Sensor (measurement)
x1 = procX + procW;          y1 = procY + procH/2;
x2 = sensX;                  y2 = sensY + sensH/2;
annotation('arrow', [nx(x1) nx(x2)], [ny(y1) ny(y2)], ...
           'LineWidth', arrowLW, ...
           'HeadLength', headLen, ...
           'HeadWidth', headWidth);

text((x1+x2)/2, y1 + 0.55, ...
    '$y_k^{i} = H_i x_k + v_k^{i}$', ...
    'Interpreter', 'latex', ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'bottom', ...
    'FontSize', fontSzSmall);

% 4.2 Sensor -> Fusion (quantized innovation)
x3 = sensX + sensW;          y3 = sensY + sensH/2 + 0.1;
x4 = fusX;                   y4 = fusY + fusH/2 + 0.1;
annotation('arrow', [nx(x3) nx(x4)], [ny(y3) ny(y4)], ...
           'LineWidth', arrowLW, ...
           'HeadLength', headLen, ...
           'HeadWidth', headWidth);

text((x3+x4)/2, y3 - 0.6, ...
    'Quantized innovation $\tilde{\epsilon}_k^{i}$', ...
    'Interpreter', 'latex', ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'top', ...
    'FontSize', fontSzSmall);

% 4.3 Fusion -> output (state estimate)
x5 = fusX + fusW;            y5 = fusY + fusH/2;
x6 = 8.3;                    y6 = y5;     % 明确 < xMax=9
annotation('arrow', [nx(x5) nx(x6)], [ny(y5) ny(y6)], ...
           'LineWidth', arrowLW, ...
           'HeadLength', headLen, ...
           'HeadWidth', headWidth);

text(x6 + 0.05, y6 + 0.35, ...
    'State estimate $\hat{x}_k$', ...
    'Interpreter', 'latex', ...
    'HorizontalAlignment', 'left', ...
    'VerticalAlignment', 'bottom', ...
    'FontSize', fontSzSmall);

%% 5) Final
axis(ax, [0 xMax 0 yMax]);
axis(ax, 'off');
set(fig, 'PaperPositionMode', 'auto');

% 保存为 EPS
print(fig, '-depsc2', 'fig_system_block.eps');
